// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PracticalTwenty.Data.Contexts;

#nullable disable

namespace PracticalTwenty.Data.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20230714003241_AddApplicationLogs")]
    partial class AddApplicationLogs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PracticalTwenty.Data.Models.ApplicationLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Area")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ControllerName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("IpAddress")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("IsFirstLogin")
                        .HasColumnType("char(1)");

                    b.Property<string>("LangId")
                        .HasColumnType("varchar(2)");

                    b.Property<DateTime>("LoggedInAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LoggedOutAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LoginStatus")
                        .HasColumnType("char(1)");

                    b.Property<string>("PageAccessed")
                        .HasColumnType("varchar(500)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(2)");

                    b.Property<string>("SessionId")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("UrlReferrer")
                        .HasColumnType("varchar(500)");

                    b.Property<string>("UserId")
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.ToTable("ApplicationLogs");
                });

            modelBuilder.Entity("PracticalTwenty.Data.Models.Audit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AffectedColumns")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimaryKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TableName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("PracticalTwenty.Data.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "bhavin@gmail.com",
                            Firstname = "Bhavin",
                            LastName = "Kareliya",
                            Password = "123123"
                        },
                        new
                        {
                            Id = 2,
                            Email = "jil@gmail.com",
                            Firstname = "Jil",
                            LastName = "Patel",
                            Password = "123123"
                        },
                        new
                        {
                            Id = 3,
                            Email = "vipul@gmail.com",
                            Firstname = "Vipul",
                            LastName = "Kumar",
                            Password = "123123"
                        },
                        new
                        {
                            Id = 4,
                            Email = "abhi@gmail.com",
                            Firstname = "Abhi",
                            LastName = "Dasadiya",
                            Password = "123123"
                        },
                        new
                        {
                            Id = 5,
                            Email = "jay@gmail.com",
                            Firstname = "Jay",
                            LastName = "Gohel",
                            Password = "123123"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
